version: "3.8"
services:
  sb-app:
    build: .
    container_name: "mongo-demo"
    ports:
      - 9090:9090
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017